security:
    encoders:
       EspritUserBundle\Entity\User: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
         main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check    
                default_target_path: AppartooParisGestionIndex 
            logout:
                path:       fos_user_security_logout
                target:     /login
            remember_me:
                key:        %secret%
                lifetime: 604800 #1 week in seconds


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }